# This workflow runs a basic check on pushes and PRs

name: CI check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Run sanitizing checks

    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip' # caching pip dependencies

      - name: Install project with dev packages and Nox
        run: |
          pip install nox
          pip install .[dev]

      - name: Run Nox check session
        run: |
          nox -s check -- CI
