# This workflow runs a basic check on pushes and PRs

name: CI check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - name: Install dev dependencies
        run: |
          pip install nox
          nox -s install
          source ./.nox/install/bin/activate
      
      - name: Run nox check session
        run: |
          nox -s check
